# Generated by Django 4.1.1 on 2022-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
