# Generated by Django 4.1.3 on 2022-11-07 12:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_user_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_muscle', models.CharField(max_length=100)),
                ('rounds', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('gym', models.BooleanField()),
                ('hypertrophy', models.BooleanField()),
                ('weight_loss', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='carbs',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='fat',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='user',
            name='protein',
            field=models.IntegerField(default=400),
        ),
    ]
