# Generated by Django 4.1.3 on 2022-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='workout',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout'),
            preserve_default=False,
        ),
    ]
