# Generated by Django 4.1.3 on 2022-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(default=500),
        ),
    ]
