# Generated by Django 4.1.3 on 2022-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_routine_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='gym',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='hypertrophy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight_loss',
            field=models.BooleanField(default=True),
        ),
    ]
