# Generated by Django 4.1.3 on 2022-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_workout_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(default=2000),
        ),
    ]
