# Generated by Django 4.1.3 on 2022-11-24 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_user_daily_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='daily_calories',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='daily_exercise',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='daily_meals',
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_balance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
