# Generated by Django 4.1.3 on 2022-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_workout_gym_workout_hypertrophy_workout_weight_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Random workout', max_length=100),
        ),
    ]
