# Generated by Django 4.1.3 on 2022-11-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_daily_daily_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to=settings.AUTH_USER_MODEL),
        ),
    ]
