# Generated by Django 4.1.3 on 2022-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_alter_daily_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('DIN', 'Dinner'), ('LU', 'Lunch'), ('SN', 'Snack')], max_length=20),
        ),
    ]
