# Generated by Django 4.1.3 on 2022-11-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_alter_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='daily_breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_breakfast', to='fitness.meal'),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_dinner', to='fitness.meal'),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_lunch', to='fitness.meal'),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_snack', to='fitness.meal'),
        ),
    ]
