# Generated by Django 4.1.3 on 2022-11-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_daily_daily_breakfast_daily_daily_dinner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.routine'),
        ),
    ]
