# Generated by Django 4.1.3 on 2022-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_alter_calendar_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calories_left',
            field=models.IntegerField(default=2000),
        ),
    ]
