# Generated by Django 4.1.3 on 2022-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_calendar_calories_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
