# Generated by Django 4.1.3 on 2022-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Legs', 'Legs'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Abs', 'Abs')], max_length=100),
        ),
    ]
