# Generated by Django 4.1.3 on 2022-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_alter_exercise_target_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Home', 'Home')], default='Gym', max_length=20),
        ),
    ]
