version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTRES_DB=fitness
      - POSTGRES_USER=wer08
      - POSTGRES_PASSWORD=M0rg0th&CO
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

  celery:
    build: .
    command: celery -A final_project worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
  celery-beat:
    build: .
    command: celery -A final_project beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq

volumes:
    rabbitmq_data:
    rabbitmq_log:
        

    


